name: C/C++ CI

on:
  push:
    branches: [ "android14" ]
  pull_request:
    branches: [ "android14" ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: make
      run: ./make.sh

    - name: Upload assets
      uses: actions/upload-artifact@v4.3.5
      with:
          name: lptools
          path: bin
